user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Servidor Node.js backend
    upstream node_backend {
        server 127.0.0.1:3000;
        keepalive 64;
    }

    server {
        listen 80;
        server_name www.istbrasil.org.br istbrasil.org.br;
        root /var/www/istbrasil.org.br/html; # Caminho para os arquivos de build do Angular
        index index.html index.htm;

        # Redirecionar para HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name www.istbrasil.org.br istbrasil.org.br;

        # Configure os caminhos para seus certificados SSL
        # ssl_certificate /etc/letsencrypt/live/istbrasil.org.br/fullchain.pem;
        # ssl_certificate_key /etc/letsencrypt/live/istbrasil.org.br/privkey.pem;

        root /var/www/istbrasil.org.br/html; # Caminho para os arquivos de build do Angular
        index index.html index.htm;

        # Proxy para a API Node.js
        location /api/ {
            proxy_pass http://node_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Roteamento para o Angular
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
