#!/usr/bin/env bash
# Real Linux filesystem integration. Fixtures are generated by Node under /tmp.
set -Eeuo pipefail
[[ $(uname -s) == Linux ]] || { printf 'Linux required; integration suite was NOT executed.\n' >&2; exit 1; }
[[ $(id -u) != 0 ]] || { printf 'Run isolated tests as a non-root user.\n' >&2; exit 1; }
SOURCE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
node --test "$SOURCE/tests/deploy-backup.test.mjs"
